### ISSUE TITLE
Exception NameError: PID file '/var/run/doorpi.pid' not locked

### ISSUE THREAD

**Issue by motom001** [motom001/DoorPi#11]
2014-12-24 11:09:40,889 [DEBUG] [doorpi] init
2014-12-24 11:09:40,896 [ERROR] [root] Exception NameError: PID file '/var/run/doorpi.pid' not locked
Traceback (most recent call last):
File "/home/pi/DoorPi//doorpi/service.py", line 44, in 
try: daemon_runner.do_action()
File "/usr/lib/pymodules/python2.7/daemon/runner.py", line 186, in do_action
func(self)
File "/usr/lib/pymodules/python2.7/daemon/runner.py", line 149, in stop
"PID file %(pidfile_path)r not locked" % vars())
DaemonRunnerStopFailureError: PID file '/var/run/doorpi.pid' not locked

**Comment by motom001** [comment]
Ergänzung von:
http://www.forum-raspberrypi.de/Thread-haussteuerung-doorpi-voip-wechselsprechanlage-tuersprechanlage?pid=126802#pid126802


Fehler tritt auch auf, wenn ein restart angeordnet wird, aber DoorPi vorher gar nicht lief:
Beispiel:

pi@raspberrypi ~/DoorPi $ sudo service doorpi restart
Restarting server
Stopping server
2015-01-10 13:54:32,967 [INFO]          [__main__]
VoIP Door-Intercomstation with Raspberry Pi (optional PiFace) 2.0 RC1 #48

Author: Thomas Meissner <thomas@meissner.me>
URL: <https://github.com/motom001/DoorPi>

2015-01-10 13:54:32,973 [DEBUG]         [__main__] loaded with arguments: ['/home/pi/DoorPi//doorpi/main.py', 'stop']
2015-01-10 13:54:33,011 [DEBUG]         [doorpi] __init__
2015-01-10 13:54:33,019 [ERROR]         [__main__] Exception NameError: PID file '/var/run/doorpi.pid' not locked
Traceback (most recent call last):
  File "/home/pi/DoorPi//doorpi/main.py", line 101, in main_as_daemon
    try:                        daemon_runner.do_action()
  File "/usr/lib/pymodules/python2.7/daemon/runner.py", line 186, in do_action
    func(self)
  File "/usr/lib/pymodules/python2.7/daemon/runner.py", line 149, in _stop
    "PID file %(pidfile_path)r not locked" % vars())
DaemonRunnerStopFailureError: PID file '/var/run/doorpi.pid' not locked
2015-01-10 13:54:33,028 [DEBUG]         [doorpi] destroy
Starting server
2015-01-10 13:54:34,210 [INFO]          [__main__]
VoIP Door-Intercomstation with Raspberry Pi (optional PiFace) 2.0 RC1 #48

Author: Thomas Meissner <thomas@meissner.me>
URL: <https://github.com/motom001/DoorPi>
