### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '/var/log/doorpi/doorpi.log'

### ISSUE THREAD

**Issue by motom001** [motom001/DoorPi#114]
```
pi@raspberrypi ~ $ sudo service doorpi start
[....] Starting VoIP Intercom Service: doorpiTraceback (most recent call last):
  File "/usr/local/bin/doorpi_cli", line 9, in <module>
    load_entry_point('DoorPi==2.4.1.0', 'console_scripts', 'doorpi_cli')()
  File "/usr/local/lib/python2.7/dist-packages/DoorPi-2.4.1.0-py2.7.egg/doorpi/main.py", line 174, in entry_point
    raise SystemExit(main_as_daemon(sys.argv))
  File "/usr/local/lib/python2.7/dist-packages/DoorPi-2.4.1.0-py2.7.egg/doorpi/main.py", line 120, in main_as_daemon
    backupCount=10
  File "/usr/lib/python2.7/logging/handlers.py", line 117, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python2.7/logging/handlers.py", line 64, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python2.7/logging/__init__.py", line 901, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 924, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: '/var/log/doorpi/doorpi.log'
 failed!
```
http://www.forum-raspberrypi.de/Thread-haussteuerung-doorpi-voip-wechselsprechanlage-tuersprechanlage-mit-video-support?pid=175972#pid175972

**Comment by motom001** [comment]
Workaround ist:
```
sudo mkdir /var/log/doorpi
sudo chown -R pi /var/log/doorpi
sudo chown -R pi /var/log/doorpi
```
zukünftig werde ich mir was überlegen müssen, da ein start von DoorPi mit und ohne sudo möglich sein soll. Ohne sudo dürfte es aber vermutlich keine Verzeichnisse unter /var/log/ anlegen.
Eventuell gibt es in der setup.py die Möglichkeit das zu erledigen.

**Comment by motom001** [comment]
Mögliche Lösung ist hier:
https://docs.python.org/2/distutils/setupscript.html#installing-additional-files

**Comment by motom001** [comment]
Merker für später:
```

    ___                  ___ _
   /   \___   ___  _ __ / _ (_)  VoIP Door-Intercomstation with Raspberry Pi
  / /\ / _ \ / _ \| '__/ /_)/ |  version:   2.4.1.1
 / /_// (_) | (_) | | / ___/| |  license:   CC BY-NC 4.0
/___,' \___/ \___/|_| \/    |_|  URL:       <https://github.com/motom001/DoorPi>

Authors:    Thomas Meissner <motom001@gmail.com>
Supporter:  Phillip Munz <office@businessaccess.info>
            Hermann Dötsch <doorpi1@gmail.com>
            Dennis Häußler <haeusslerd@outlook.com>
            Hubert Nusser <hubsif@gmx.de>
            Michael Hauer <frrr@gmx.at>
            Andreas Schwarz <doorpi@schwarz-ketsch.de>
            Max Rößler <max_kr@gmx.de>
            missing someone? -> sorry -> mail me

Traceback (most recent call last):
  File "/home/pi/virtualenv/python2.7/bin/doorpi_cli", line 9, in <module>
    load_entry_point('DoorPi==2.4.1.1', 'console_scripts', 'doorpi_cli')()
  File "/home/pi/virtualenv/python2.7/local/lib/python2.7/site-packages/DoorPi-2.4.1.1-py2.7.egg/doorpi/main.py", line 176, in entry_point
    raise SystemExit(main_as_daemon(sys.argv))
  File "/home/pi/virtualenv/python2.7/local/lib/python2.7/site-packages/DoorPi-2.4.1.1-py2.7.egg/doorpi/main.py", line 132, in main_as_daemon
    from daemon import runner
ImportError: cannot import name runner
(python2.7)pi@doorpi1b ~/DoorPi/development $ python
Python 2.7.3 (default, Mar 18 2014, 05:13:23)
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import daemon
>>> daemon.__file__
'/home/pi/virtualenv/python2.7/local/lib/python2.7/site-packages/daemon-1.1-py2.7.egg/daemon.pyc'
>>>
```

**Comment by Nea74** [comment]
Guten Morgen, ich denke hier kann geschlossen werden. Die neue Installation läuft sehr gut.
