### ISSUE TITLE
DoorPi wird bei einem Restart nicht wieder gestartet.

### ISSUE THREAD

**Issue by Nea74** [motom001/DoorPi#132]

**Comment by Nea74** [comment]
Aha warum kann ich hier nur eine Person angeben? Seltsam.

**Comment by maxkr2** [comment]
Hi Nea,

ich hatte da als Abhilfe mal einen "sleep 5" vorgeschlagen, aber vielleicht reicht die Zeit nicht (mehr). Kannst du da mal mit einem höheren Wert experemtieren. Gut wäre es auch evt. in einem zweiten Fenster zu schauen, ob der Prozess wirklich beendet wurde:
ps -ef | grep doorpi | grep -v grep
...sollte dir zum Ende des sleeps keine Einträge mehr anzeigen. DoorPi sollte anschließend nur einmal auftauchen und eine andere PID haben...

Viele Grüße,
Max

**Comment by motom001** [comment]
Wer kann mit bash in diesem Script folgendes realisieren:
- Restart wird aufgerufen
- Status prüft ob DoorPi beendet ist
-- wenn nein, dann warte 3 Sekunden und prüfe erneut
-- wenn ja, dann warte weitere 3 Sekunden und starte DoorPi erneut

Sollte in bash doch kein Problem sein, nur eben kann ich es nicht :(

**Comment by maxkr2** [comment]
Hi Thomas,
ja kann ich mir gerne mal anschauen. Ein wirklicher Experte bin ich aber leider auch nicht, beiße mich halt so durch.

Muss dich leider mit einem neuen/ alten Problem nerven: Mein DoorPi startet nicht mehr:
```Traceback (most recent call last):
  File "/usr/local/bin/doorpi_cli", line 9, in <module>
    load_entry_point('DoorPi==2.4.1.6', 'console_scripts', 'doorpi_cli')()
  File "/usr/local/lib/python2.7/dist-packages/DoorPi-2.4.1.6-py2.7.egg/doorpi/main.py", line 168, in entry_point
    raise SystemExit(main_as_daemon(sys.argv))
  File "/usr/local/lib/python2.7/dist-packages/DoorPi-2.4.1.6-py2.7.egg/doorpi/main.py", line 123, in main_as_daemon
    from daemon import runner
  File "/usr/local/lib/python2.7/dist-packages/python_daemon-UNKNOWN-py2.7.egg/daemon/runner.py", line 35, in <module>
    from . import pidfile
  File "/usr/local/lib/python2.7/dist-packages/python_daemon-UNKNOWN-py2.7.egg/daemon/pidfile.py", line 18, in <module>
    from lockfile.pidlockfile import PIDLockFile
ImportError: No module named pidlockfile
 failed!```

...habe schon ein Update gemacht auf 2.4.1.6. Wahrscheinlich ist irgendein Raspbian-Update die Ursache dafür...?! Vielleicht hast du einen Tipp, dann ist das testen des Restarts einfacher...

**Comment by motom001** [comment]
```
sudo pip uninstall python-daemon
sudo pip --upgrade pip
sudo pip --upgrade wheel
sudo pip --upgrade setuptools
sudo pip install --upgrade doorpi
```

**Comment by maxkr2** [comment]
Danke Thomas,
davon abgesehen, dass pip-2.7 auf einmal weg war, Raspbian nur 2.6 und die 3.x Python-Version anbietet, habe ich die Installation noch mal durchlaufen lassen. Der Python-Daemon, der durch doorpi installiert wird ist:
```Collecting python-daemon (from doorpi)
  Using cached python_daemon-2.0.6-py2.py3-none-any.whl```
Leider keine Änderung nach dem Update. Ich erhalte immer noch die o.g. FM....

Der manuelle Start geht übrigens. Es liegt mal wieder am Daemon...?!
Viele Grüße,
Max

**Comment by motom001** [comment]
Nochmal den python-daemon deinstallieren und diese Datei löschen:
/usr/local/lib/python2.7/dist-packages/python_daemon-UNKNOWN-py2.7.egg

Und dann doorpi neu installieren...

**Comment by maxkr2** [comment]
Hi Thomas,
die ```/usr/local/lib/python2.7/dist-packages/python_daemon-UNKNOWN-py2.7.egg``` findet er bei mir nicht. Vor bzw. nach der Deinstallation ist ```/usr/local/lib/python2.7/dist-packages/python_daemon-2.0.6.dist-info/``` zu finden.

Nach der Neuinstallation leider nach wie vor die gleiche FM.
