### ISSUE TITLE
Exception NameError: No PiFace Digital board detected (hardware_addr=0, bus=0, chip_select=0).

### ISSUE THREAD

**Issue by motom001** [motom001/DoorPi#29]
Meldung aus Issue #17 
```
2015-01-12 20:34:10,505 [DEBUG] [main] loaded with arguments: ['./main.py', '--configfile', '/home/pi/DoorPi/conf/doorpi.cfg']
2015-01-12 20:34:10,510 [DEBUG] [doorpi] init
2015-01-12 20:34:10,515 [DEBUG] [doorpi] run
2015-01-12 20:34:10,520 [DEBUG] [doorpi] prepare
2015-01-12 20:34:10,524 [DEBUG] [doorpi] givven arguments argv: Namespace(configfile=)
2015-01-12 20:34:10,530 [DEBUG] [conf.config_object] load_config ()
2015-01-12 20:34:10,535 [DEBUG] [conf.config_object] use configfile: /home/pi/DoorPi/conf/doorpi.cfg
2015-01-12 20:34:10,559 [DEBUG] [conf.config_object] init
2015-01-12 20:34:10,563 [TRACE] [conf.config_object] get_from_config
2015-01-12 20:34:10,583 [TRACE] [conf.config_object] get for key typ in section keyboard (default: autodetect)
2015-01-12 20:34:10,588 [TRACE] [conf.config_object] get_string for key typ in section keyboard (default: autodetect)
2015-01-12 20:34:10,592 [TRACE] [conf.config_object] section 'keyboard' doesn't exist
2015-01-12 20:34:10,597 [TRACE] [conf.config_object] return default 'autodetect
2015-01-12 20:34:10,602 [TRACE] [conf.config_object] get_int for key bouncetime in section keyboard (default: 5000)
2015-01-12 20:34:10,606 [TRACE] [conf.config_object] get_string for key bouncetime in section keyboard (default: )
2015-01-12 20:34:10,611 [TRACE] [conf.config_object] section 'keyboard' doesn't exist
2015-01-12 20:34:10,615 [TRACE] [conf.config_object] return default '
2015-01-12 20:34:10,620 [TRACE] [conf.config_object] get_keys for section InputPins
2015-01-12 20:34:10,626 [TRACE] [conf.config_object] get_keys for section OutputPins
2015-01-12 20:34:10,631 [TRACE] [keyboard.KeyboardInterface] autodetect
2015-01-12 20:34:10,635 [TRACE] [keyboard.KeyboardInterface] load_piface
2015-01-12 20:34:10,642 [DEBUG] [keyboard.from_piface] keyboard.from_piface loaded
2015-01-12 20:34:10,739 [DEBUG] [keyboard.AbstractBaseClass] keyboard.AbstractBaseClass loaded
2015-01-12 20:34:10,746 [DEBUG] [keyboard.from_piface] init(input_pins = ['11', '13', '15'], output_pins = ['18', '7', '16'])
2015-01-12 20:34:10,751 [TRACE] [action.handler] register Event OnKeyPressed from keyboard.from_piface
2015-01-12 20:34:10,755 [TRACE] [action.handler] register Eventsource keyboard.from_piface
2015-01-12 20:34:10,760 [DEBUG] [action.handler] event_source keyboard.from_piface was added
2015-01-12 20:34:10,764 [TRACE] [action.handler] added event_name OnKeyPressed an register source keyboard.from_piface
2015-01-12 20:34:10,925 [ERROR] [main] Exception NameError: No PiFace Digital board detected (hardware_addr=0, bus=0, chip_select=0).
Traceback (most recent call last):
File "./main.py", line 114, in main_as_application
try: doorpi.DoorPi(parsed_arguments).run()
File "/home/pi/DoorPi/doorpi/doorpi.py", line 174, in run
if not self.prepared: self.prepare(self.__parsed_arguments)
File "/home/pi/DoorPi/doorpi/doorpi.py", line 99, in prepare
self.__keyboard = load_keyboard()
File "/home/pi/DoorPi/doorpi/keyboard/KeyboardInterface.py", line 35, in load_keyboard
bouncetime = bouncetime
File "/home/pi/DoorPi/doorpi/keyboard/KeyboardInterface.py", line 41, in autodetect
try: return load_piface(input_pins, output_pins, bouncetime)
File "/home/pi/DoorPi/doorpi/keyboard/KeyboardInterface.py", line 54, in load_piface
output_pins = output_pins
File "/home/pi/DoorPi/doorpi/keyboard/from_piface.py", line 41, in __init
p.init()
File "/usr/lib/python2.7/dist-packages/pifacedigitalio/core.py", line 166, in init
raise failed_boards[0]
NoPiFaceDigitalDetectedError: No PiFace Digital board detected (hardware_addr=0, bus=0, chip_select=0).
2015-01-12 20:34:10,940 [DEBUG] [doorpi] destroy
2015-01-12 20:34:10,945 [WARNING] [action.handler] source doorpi unknown - skip fire_event OnShutdown
2015-01-12 20:34:10,949 [TRACE] [action.handler] unregister Eventsource doorpi and force_unregister is True
2015-01-12 20:34:10,954 [DEBUG] [keyboard.from_piface] destroy
Exception pifacedigitalio.core.NoPiFaceDigitalError: NoPiFaceDigitalError('There is no PiFace Digital with hardware_addr 0',) in > ignored
pi@doorberry ~/DoorPi/doorpi $
```

**Comment by motom001** [comment]
In der Fehlermeldung wird das Problem schon benannt:

    Exception NameError: No PiFace Digital board detected (hardware_addr=0, bus=0, chip_select=0).

Test mal bitte folgenden Code:

    python /usr/share/doc/python-pifacedigitalio/examples/blink.py
