### ISSUE TITLE
[ERROR]       [action.handler] error while fire action PjsipHandleEventsAction with args () and kwargs {'timeout': 50} for event_name OnTimeTick

### ISSUE THREAD

**Issue by motom001** [motom001/DoorPi#33]
Fehlermeldung:
C2015-01-27 22:42:24,050 [ERROR]       [action.handler] error while fire action PjsipHandleEventsAction with args () and kwargs {'timeout': 50} for event_name OnTimeTick
Traceback (most recent call last):
  File "/home/pi/doorpi/doorpi/action/handler.py", line 140, in fire_event_synchron
    action.run(silent)
  File "/home/pi/doorpi/doorpi/action/base.py", line 48, in run
    return self.__callback(**self.__kwargs)
  File "/home/pi/doorpi/doorpi/action/SingleActions/pjsip_handle_events.py", line 15, in pjsip_handle_events
    doorpi.DoorPi().sipphone.lib.handle_events(timeout)
  File "/usr/local/lib/python2.7/dist-packages/pjsua.py", line 2258, in handle_events
    return _pjsua.handle_events(timeout)
KeyboardInterrupt

**Comment by motom001** [comment]
Kommt vor wenn man DoorPi beenden will aber mit dem KeyboardInterrupt den handler von pjsua erwischt.
Ist nicht schlimm, der wird kurz darauf wieder aufgerufen - nur die Fehlermeldung ist unschön...
