### ISSUE TITLE
Windows 10 for Raspberry Pi 2

### ISSUE THREAD

**Issue by motom001** [motom001/DoorPi#42]
Für späteren Meilenstein:
http://dev.windows.com/en-us/featured/raspberrypi2support

Die Performance des RPi wird bei manchen an Grenzen stoßen. Speziell mit Echo-Unterdrückung und hochauflösendem Video-Signal wird es beim Single-Core 700MHz eng.
Deshalb der weite Blick voraus zum Quad-Core - eventuell mit optionalem Windows 10 um Installations und Konfiguration zu erleichtern.

**Comment by hermanthegerman2** [comment]
Genau aus diesem Grund hab ich mir heute den Raspi 2 bei Pollin bestellt ;-)

**Comment by pmunz** [comment]
hihi ich auch :P

**Comment by hermanthegerman2** [comment]
Raspberry Pi 2 ist angekommen. Werde DoorPI mal drauf testen ...
@pmunz
ist Deiner auch schon da ?

**Comment by motom001** [comment]
Kannst du bitte eventuell gleich ein paar Screenshots für das Wiki machen?

**Comment by pmunz** [comment]
Hallo , nein leider noch nicht , freu mich aber schon . aber denke morgen sollte er kommen :) bin eh krank und kann gerade nicht so .

**Comment by hermanthegerman2** [comment]
DoorPI.sh läuft ohne Probleme durch.

Nach Ausführen als App gibt´s Probleme mit Python-RPi.GPIO:

2015-02-04 19:33:38,001 [DEBUG]         [__main__] loaded with arguments: ['/home/DoorPI/doorpi/main.py', '--configfile', '/home/DoorPI/conf/doorpi.cfg']
2015-02-04 19:33:38,002 [DEBUG]         [doorpi] run
2015-02-04 19:33:38,003 [DEBUG]         [doorpi] prepare
2015-02-04 19:33:38,003 [DEBUG]         [doorpi] givven arguments argv: Namespace(configfile=<open file '/home/DoorPI/conf/doorpi.cfg', mode 'r' at 0x1ebd5a0>)
2015-02-04 19:33:38,004 [DEBUG]         [conf.config_object] load_config (<open file '/home/DoorPI/conf/doorpi.cfg', mode 'r' at 0x1ebd5a0>)
2015-02-04 19:33:38,005 [DEBUG]         [conf.config_object] use configfile: /home/DoorPI/conf/doorpi.cfg
2015-02-04 19:33:38,010 [DEBUG]         [conf.config_object] __init__
2015-02-04 19:33:38,011 [TRACE]         [conf.config_object] get_from_config
2015-02-04 19:33:38,014 [TRACE]         [conf.config_object] get_string for key typ in section keyboard (default: autodetect) returns gpio
2015-02-04 19:33:38,015 [TRACE]         [conf.config_object] get_integer for key bouncetime in section keyboard (default: 5000) returns 5000
2015-02-04 19:33:38,015 [TRACE]         [conf.config_object] get_keys for section InputPins
2015-02-04 19:33:38,016 [TRACE]         [conf.config_object] get_keys for section OutputPins
2015-02-04 19:33:38,017 [TRACE]         [keyboard.KeyboardInterface] load_gpio
2015-02-04 19:33:38,018 [DEBUG]         [keyboard.from_gpio] keyboard.from_gpio loaded
2015-02-04 19:33:38,021 [ERROR]         [__main__] Exception NameError: This module can only be run on a Raspberry Pi!
Traceback (most recent call last):
  File "/home/DoorPI/doorpi/main.py", line 145, in main_as_application
    try:                        doorpi.DoorPi(parsed_arguments).run()
  File "/home/DoorPI/doorpi/doorpi.py", line 188, in run
    if not self.__prepared: self.prepare(self.__parsed_arguments)
  File "/home/DoorPI/doorpi/doorpi.py", line 105, in prepare
    self.__keyboard = load_keyboard()
  File "/home/DoorPI/doorpi/keyboard/KeyboardInterface.py", line 35, in load_keyboard
    bouncetime = bouncetime
  File "/home/DoorPI/doorpi/keyboard/KeyboardInterface.py", line 59, in load_gpio
    import keyboard.from_gpio
  File "/home/DoorPI/doorpi/keyboard/from_gpio.py", line 8, in <module>
    import RPi.GPIO as RPiGPIO # basic for GPIO control

**Comment by hermanthegerman2** [comment]
Hab hierzu einen Thread im http://www.forum-raspberrypi.de/Thread-python-python-rpi-gpio-fuer-raspberry-pi-2 geöffnet.

**Comment by motom001** [comment]
Klingt nach dem gleichen Problem wie hier:
http://sourceforge.net/p/raspberry-gpio-python/tickets/84/

Support für Raspberry 2 ist bereits ein Ticket:
http://sourceforge.net/p/raspberry-gpio-python/tickets/95/

Grundsätzlich, sofern sich an der Ansteuerung der GPIO nichts geändert hat, könnte man das Paket hier runterladen:
http://sourceforge.net/projects/raspberry-gpio-python/files/RPi.GPIO-0.5.9.tar.gz/download

Dann entpacken und in der Datei RPi.GPIO-0.5.9\source\cpuinfo.c bearbeiten (Zeile 40)

    if (strcmp(hardware, "BCM2708") == 0 || strcmp(hardware, "BCM2835") == 0)

ändern in:

    if (strcmp(hardware, "BCM2708") == 0 || strcmp(hardware, "BCM2835") == 0 || strcmp(hardware, "BCM2836") == 0)

Der BCM2836 sollte der Code für die neue CPU sein. Eventuell noch einmal prüfen in der Datei /proc/cpuinfo mittels `cat /proc/cpuinfo`

Danach das Paket gemäß den Anleitung aus der Install.txt installieren:

>If you want to build your own version from this downloaded copy, make
>sure that you have the Python development source installed first!
>
>On Raspbian:
>$ sudo apt-get install python-dev python3-dev
>
>To install the module:
>
>$ sudo python setup.py install
>  or
>$ sudo python3 setup.py install


Sag Bescheid wenns doch Probleme gibt.

**Comment by hermanthegerman2** [comment]
Hut ab motom001,

läuft jetzt. Zur Info cat /proc/cpuinfo:

pi@raspberrypi ~/RPi.GPIO-0.5.9 $ cat /proc/cpuinfo
processor       : 0
model name      : ARMv7 Processor rev 5 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 5

processor       : 1
model name      : ARMv7 Processor rev 5 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 5

processor       : 2
model name      : ARMv7 Processor rev 5 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 5

processor       : 3
model name      : ARMv7 Processor rev 5 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 5

Hardware        : BCM2709
Revision        : a01041
Serial          : 0000000066e9c374
