### ISSUE TITLE
keyboard error

### ISSUE THREAD

**Issue by Schwa-l-be** [motom001/DoorPi#62]
2015-03-04 16:41:17,323 [ERROR]  	[doorpi] Please set pin numbering mode using GPIO.setmode(GPIO.BOARD) or GPIO.setmode(GPIO.BCM)
Traceback (most recent call last):
  File "/home/pi/DoorPi/doorpi/doorpi.py", line 163, in destroy
    self.keyboard.destroy()
  File "/home/pi/DoorPi/doorpi/keyboard/KeyboardInterface.py", line 122, in destroy
    self.__keyboards[Keyboard].destroy()
  File "/home/pi/DoorPi/doorpi/keyboard/from_gpio.py", line 49, in destroy
    self.set_output(output_pin, 0, False)
  File "/home/pi/DoorPi/doorpi/keyboard/from_gpio.py", line 80, in set_output
    RPiGPIO.output(pin, value)
RuntimeError: Please set pin numbering mode using GPIO.setmode(GPIO.BOARD) or GPIO.setmode(GPIO.BCM)

muss seit neuestem die "Anordnung" in der config eingestellt werden? War doch bis jetzt standardmäßig BOARD. In der from_gpio.py ist es auch noch immer so hinterlegt.

2015-03-04 16:53:20,437 [ERROR]  	[keyboard.KeyboardInterface] keyboard virtuell not found @ keyboard.from_filesystem (msg: No module named watchdog.observers)
Traceback (most recent call last):
  File "/home/pi/DoorPi/doorpi/keyboard/KeyboardInterface.py", line 43, in load_single_keyboard
    keyboard = importlib.import_module('keyboard.from_'+keyboard_type).get(
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/pi/DoorPi/doorpi/keyboard/from_filesystem.py", line 12, in <module>
    from watchdog.observers import Observer
ImportError: No module named watchdog.observers
2015-03-04 16:53:20,449 [ERROR]  	[keyboard.KeyboardInterface] couldn't load keyboard virtuell

wollte das virtuelle Keyboard auch mal testen aber anscheinend läuft bei mir einiges falsch...

**Comment by motom001** [comment]
Das sollte helfen:
apt-get install python-pip
pip install watchdog

Ist so auch im (commit)[https://github.com/motom001/DoorPi/commit/c671b5c752bb6c12c41ff62084b0a9a688efa293] und im issue #45 vermerkt, fehlt aber noch im Installscript, da noch keine Zeit war.

**Comment by Schwa-l-be** [comment]
sorry dass ich das ganze nochmals aufmache aber seit ich auf das virtuell + gpio umgestiegen bin nimmt er mir keine Aktionen mehr.. auch mit meiner alten config.

hier mal der neue Teil:
[DTMF]
"#" = out:door,0,1,3
"0" = out:licht,0,1,1

[keyboards]
virtuell = filesystem
gpio = gpio

[gpio_keyboard]
bouncetime = 20

[gpio_InputPins]
18 = call:**9

[gpio_OutputPins]
3 = licht
5 = door
7 = strom
11 = lautsprecher

[virtuell_keyboard]
reset_input = true
base_path_input = /var/DoorPI/keyboard/inputs/
base_path_output = /var/DoorPI/keyboard/outputs

[virtuell_InputPins]
tuerauf = out:door,0,1,3

hab ich da einen Fehler?

**Comment by motom001** [comment]
Schickst du mir mal bitte deine logdatei per Mail?

**Comment by Schwa-l-be** [comment]
die ganze Sache scheint nicht am Keyboard zu liegen sondern an pjsua.
Es wird eine Verbindung mit meiner FritzBox hergestellt aber sobald ein Gespräch aufgebaut werden soll beendet sich pjsua deshalb kann ich auch kein Tür öffnen und bekomme kein Klingeln signalisiert. 
Jedoch hab ich keine Ahnung wie ich das Ganze lösen soll.

**Comment by motom001** [comment]
bitte noch einmal mit linphone testen - sollte damit vielleicht schon behoben sein....

**Comment by Schwa-l-be** [comment]
mit linphone funktioniert alles wie es soll
