### ISSUE TITLE
Address already in use

### ISSUE THREAD

**Issue by motom001** [motom001/DoorPi#72]
```
2015-05-23 13:04:44,506 [DEBUG] [conf.config_object] create new key ip in section DoorPiWeb with value ''
2015-05-23 13:04:44,508 [TRACE] [conf.config_object] get_string for key ip in section DoorPiWeb (default: ) returns 
2015-05-23 13:04:44,512 [TRACE] [conf.config_object] no value found - use default
2015-05-23 13:04:44,514 [TRACE] [conf.config_object] get_integer for key port in section DoorPiWeb (default: 80) returns 80
2015-05-23 13:04:44,517 [INFO] [status.webserver] initial WebService at ip and port 80
2015-05-23 13:04:44,522 [ERROR] [__main__] Exception NameError: [Errno 98] Address already in use
Traceback (most recent call last):
File "/home/DoorPI/doorpi/main.py", line 159, in main_as_application
try: doorpi.DoorPi(parsed_arguments).run()
File "/home/DoorPI/doorpi/doorpi.py", line 214, in run
if not self.__prepared: self.prepare(self.__parsed_arguments)
File "/home/DoorPI/doorpi/doorpi.py", line 128, in prepare
self.__webserver = load_webserver().start()
File "/home/DoorPI/doorpi/status/webserver.py", line 29, in load_webserver
return DoorPiWeb(server_address, DoorPiWebRequestHandler)
File "/usr/lib/python2.7/SocketServer.py", line 419, in __init__
self.server_bind()
File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
SocketServer.TCPServer.server_bind(self)
File "/usr/lib/python2.7/SocketServer.py", line 430, in server_bind
self.socket.bind(self.server_address)
File "/usr/lib/python2.7/socket.py", line 224, in meth
return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use
2015-05-23 13:04:44,548 [DEBUG] [doorpi] destroy doorpi
```

gemeldet von [waldler](http://www.forum-raspberrypi.de/User-waldler)

**Comment by motom001** [comment]
Workaround: reboot your pi

DoorPi couldn't bind to address, mostly because doorpi wasn't successfully shutdown and webserver is still running. If this problem is still exists after reboot, then there is another application running on port 80. In this case modify your doorpi config or stop the other running application (apache or else)
